# Generated by Django 5.1.6 on 2025-02-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sp500', models.FloatField()),
                ('nasdaq', models.FloatField()),
                ('dowjones', models.FloatField()),
                ('crude_oil', models.FloatField()),
                ('gold', models.FloatField()),
                ('eur_usd', models.FloatField()),
                ('treasury_10y', models.FloatField()),
                ('vix', models.FloatField()),
                ('is_abnormal', models.BooleanField()),
            ],
        ),
    ]
