# Generated by Django 5.1.6 on 2025-02-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIMODEL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='variation_crude_oil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_dowjones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_eur_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_gold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_nasdaq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_sp500',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_treasury_10y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='variation_vix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
